name: packages Builder

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**  
      
env:
  REPO_URL: https://github.com/wixxm/OpenWrt-24.10
  REPO_BRANCH: main
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: op1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }} Packages
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        tag:
          - WikjxWrt-packages

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 10240
        temp-reserve-mb: 100
        swap-size-mb: 8192
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        curl -sSL https://raw.githubusercontent.com/wixxm/wikjxwrt-auto/main/hj.sh -o hj.sh
        sudo chmod +x hj.sh
        sudo bash hj.sh
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Load custom feeds
      run: |
        curl -sSL https://raw.githubusercontent.com/wixxm/wikjxwrt/main/wikjxwrt.sh -o wikjxwrt.sh
        chmod +x wikjxwrt.sh
        ./wikjxwrt.sh

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload packages
      run: |
        mkdir -p /tmp/openwrt_lite/${{ matrix.arch }}/
        if [ -d "/tmp/openwrt_lite/${{ matrix.arch }}" ]; then
          echo "目录 /tmp/openwrt_lite/${{ matrix.arch }} 创建成功"
        else
          echo "目录创建失败！" >&2
          exit 1
        fi
        mv openwrt/bin/packages/${{ matrix.arch }}/wikjxwrt/* /tmp/openwrt_lite/${{ matrix.arch }}/
        if [ "$(ls -A /tmp/openwrt_lite/${{ matrix.arch }})" ]; then
          echo "文件已成功移动到 /tmp/openwrt_lite/${{ matrix.arch }}/"
        else
          echo "文件移动失败，目标目录为空！" >&2
          exit 1
        fi
        curl -sO https://raw.githubusercontent.com/${{ github.repository }}/config/generate-index-24.10.sh
        bash generate-index-24.10.sh /tmp/openwrt_lite/${{ matrix.arch }}
        tar -cJvf /tmp/openwrt_lite/WikjxWrt-packages-${{ matrix.arch }}.tar.xz -C /tmp/openwrt_lite ${{ matrix.arch }}
        if [ -f "/tmp/openwrt_lite/WikjxWrt-packages-${{ matrix.arch }}.tar.xz" ]; then
          echo "tarball 文件生成成功"
        else
          echo "tarball 文件生成失败！" >&2
        exit 1
        fi

    - name: Create release
      uses: ncipollo/release-action@v1.14.0
      with:
        name: ${{ matrix.tag }}
        allowUpdates: true
        tag: ${{ matrix.tag }}
        replacesArtifacts: true
        token: ${{ secrets.OPENWRT_WORKFLOW_TOKEN }}
        artifacts: /tmp/openwrt_lite/WikjxWrt-packages-${{ matrix.arch }}.tar.xz

        
  push:
    needs: build
    name: Push Built Packages
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: opkg
      
      - name: Download packages
        run: |
          echo "latest_release=$(TZ='Asia/Hong_Kong' date +'%Y%m%d')" >> $GITHUB_ENV
          git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch WikjxWrt-packages/**/*.ipk' --prune-empty --tag-name-filter cat HEAD
          curl -LO https://github.com/${{ github.repository }}/releases/download/WikjxWrt-packages/WikjxWrt-packages-x86_64.tar.xz
          rm -rf WikjxWrt-packages
          mkdir -p WikjxWrt-packages
          tar -xf WikjxWrt-packages-x86_64.tar.xz -C WikjxWrt-packages
          rm -f WikjxWrt-packages-x86_64.tar.xz

      - name: Git push
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          git add WikjxWrt-packages/*
          git commit -sm "🏅 UP packages-24.10 - $timestamp"
          git push --force


        
